language: php
php:
  - 7.3
  - 7.4
dist: xenial
env:
  global:
    - REDIS_HOST=localhost REDIS_PORT=6379
    - TRAVIS=true
  matrix:
    - DB_ENGINE=mysql DB_HOST=localhost DB_USERNAME=root
    - DB_ENGINE=postgres DB_HOST=localhost DB_USERNAME=postgres
    - DB_ENGINE=sqlite DB_HOST=localhost DB_USERNAME=jim
services:
  - mysql
  - postgresql
  - redis-server
before_install:
  - if [ $DB_ENGINE = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE origin;'; fi
  - if [ $DB_ENGINE = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE origin_test;'; fi
  - if [ $DB_ENGINE = 'postgres' ]; then psql -c 'CREATE DATABASE origin;' -U postgres; fi
  - if [ $DB_ENGINE = 'postgres' ]; then psql -c 'CREATE DATABASE origin_test;' -U postgres; fi
  - pecl channel-update pecl.php.net
  - pecl install mailparse
  - echo yes | pecl install -f apcu
  - echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - composer install --prefer-source --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - php php-coveralls.phar --verbose
cache:
  directories:
    - $HOME/.composer/cache/files
after_success:
  - bash <(curl -s https://codecov.io/bash)
